### ISSUE TITLE
docker build fails with configuration error

### ISSUE THREAD

**Issue by jshank** [smartmontools/docker-build#1]
`docker build -t smartmontools/docker-build .` generates the error below

`checking for OpenSSL_add_all_ciphers in -lcrypto... no
configure: error: Cannot build without libcrypto (OpenSSL)
Error 0 in ./configure
The command '/bin/sh -c cd /tmp     && wget https://github.com/mackyle/xar/archive/xar-${XAR_VERSION}.tar.gz     && tar -xvzf xar-${XAR_VERSION}.tar.gz     && cd xar-xar-${XAR_VERSION}/xar     && ./autogen.sh && ./configure && make && make install     && cd / && rm -rf /tmp/xar-xar-${XAR_VERSION} /tmp/xar-${XAR_VERSION}.tar.gz' returned a non-zero code: 1
`

**Comment by samm-git** [comment]
@jshank Please take a look on the circle ci recipe to build smarmtontools package.

**Comment by samm-git** [comment]
@jshank

**Comment by samm-git** [comment]
@jshank ah, got it now. Seems that recent openssl update broken xar package. Reverting to 1.0 OpenSSL dev headers.

**Comment by samm-git** [comment]
Fixed in https://github.com/smartmontools/docker-build/commit/eb57d358548706588732e6f66ddc910598fdb96f
