### ISSUE TITLE
Is this image intended for use?

### ISSUE THREAD

**Issue by cmsj** [smartmontools/docker-build#4]
I was just looking around for a smartmontools docker image and discovered this official one. Is it intended for end-user use, or is it primarily for CI?

**Comment by chrfranke** [comment]
This image does not contain smartmontools. It contains the (cross-)toolchains we use to do CI and release builds. Of course it can be used by other projects if the provided tools are sufficient.

**Comment by cmsj** [comment]
oh! well then that answers that :D

thanks!

**Comment by samm-git** [comment]
btw, if you think that official docker will be beneficial for the Linux users - its not a hard thing to add one.
